#!/usr/bin/env node
let MySQLModelGenerator = require("./dist/MySQLModelGenerator");
let args = process.argv;
let params = {};
for(var i = 2; i < process.argv.length; i++) {
    let statement = args[i];
    let statement_tokens = statement.split('=');
    console.log(statement_tokens)
    let replace_regex = /^([-]+)/g
    let key = statement_tokens[0].replace(replace_regex, ''); //Strip leading dashes
    let value = statement_tokens[1];
    if(key !== undefined && value !== undefined){
        params[key] = value;
    }
}
let {host, database, password, user, outfolder} = params;
let config = {
    host, database, password, user
}
if(!outfolder){
    throw new Error(`Out folder must be specified in the format outfolder=/path/to/model/folder`);
}
let generator = new MySQLModelGenerator(config);
generator.generate(outfolder).then(() => {
    console.log(`Models generated successfully.`);
    generator.db.closeConnection();
}).catch(err => {
    console.error(`Errors occurred generating models.`);
    console.error(err);
});